spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${url}
    username: ${user_name}
    password: ${password}

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      use-new-id-generate-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true

  thymeleaf:
    cache: false